name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglu1-mesa-dev mesa-common-dev xorg-dev libasound2-dev
          version: 1.2
      - name: Build hot reload
        run: odin run . -- -hot

      - name: Build release
        run: odin run . -- -release

      - name: Build web
        run: odin run . -- -web

      - name: Build hot reload (debug)
        run: odin run . -- -hot-reload -debug

      - name: Build release (debug)
        run: odin run . -- -release -debug

      - name: Build web (debug)
        run: odin run . -- -web -debug

  build_macos:
    name: MacOS
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{matrix.os}}
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false

      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4

      - name: Build hot reload
        run: odin run . -- -hot-reload

      - name: Build release
        run: odin run . -- -release

      - name: Build web
        run: odin run . -- -web

      - name: Build hot reload (debug)
        run: odin run . -- -hot-reload -debug

      - name: Build release (debug)
        run: odin run . -- -release -debug

      - name: Build web (debug)
        run: odin run . -- -web -debug

  # build_windows:
  #   name: Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: laytan/setup-odin@v2
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release: false
  #
  #     - uses: mymindstorm/setup-emsdk@v14
  #
  #     - uses: actions/setup-python@v5
  #
  #     - uses: actions/checkout@v4
  #
  #     - uses: ilammy/msvc-dev-cmd@v1
  #
  #     - name: Build hot reload
  #       run: odin run . -- -hot-reload
  #
  #     - name: Build release
  #       run: odin run . -- -release
  #
  #     - name: Build web
  #       run: odin run . -- -web
  #
  #     - name: Build hot reload (debug)
  #       run: odin run . -- -hot-reload -debug
  #
  #     - name: Build release (debug)
  #       run: odin run . -- -release -debug
  #
  #     - name: Build web (debug)
  #       run: odin run . -- -web -debug
